services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///switches.db
    restart: unless-stopped

  # Optional: Add Redis for caching distributor API calls
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: