services:
  - type: web
    name: netgear-switch-configurator
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
    numInstances: 1
    plan: starter
    port: 5000
    healthCheckPath: /
    buildCommand: ""
    startCommand: ""
    autoDeploy: false